env:
  global:
  - IMAGE_NAME=bgdevit/docker-firewall
  - REGISTRY_USER=bgdevitrobot

jobs:
  include:
  - stage: "Build Docker image"
      name: "build-amd64"
      arch: amd64
      os: linux
      language: minimal
      services: docker
      script:
      - docker build  --tag "$IMAGE_NAME" .
      - docker images